### ISSUE TITLE
maybe something wrong had happened

### ISSUE THREAD

**Issue by better319** [choiip/appinventor-docker#2]
yesterday  i  do this :docker pull choiip/appinventor-server-env:latest
something wrong had happened

![微信截图_20201229091754](https://user-images.githubusercontent.com/13842581/103252269-0a903d80-49b7-11eb-8812-711ac01157d9.png)

**Comment by better319** [comment]
developer@choiip-appinventor-server-env1:~$ ls

appengine  appengine-java-sdk-1.9.84  startserver.sh

developer@choiip-appinventor-server-env1:~$ ./startserver.sh

./startserver.sh: line 4: cd: /home/developer/appinventor-sources/appinventor: No such file or directory

**Comment by choiip** [comment]
appinventor-server-env is the image for appinventor development environment setup.
If you want the launch the appinventor, you have to build the appinventor-server image. 
```
docker build --build-arg REPO_TAG=v186a --rm -t appinventor-server:v186a -f prod.Dockerfile .
```
You may read the Makefile to learn more.

**Comment by better319** [comment]
thanks
